languageCode = "en-us"
title = "XIV ZONE"
theme = "mytheme"
summaryLength = 30
disableHugoGeneratorInject = true
enableEmoji = true
baseURL = "https://xiv.zone/"

[params]
  mainSections = ["astra"]

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
